CREATE TABLE airflow_example(
	id			INT	GENERATED BY DEFAULT AS IDENTITY,
	column1 INT,
	column2 INT
);

CREATE TABLE airflow_example_doubled(
	doubled_id			INT	GENERATED BY DEFAULT AS IDENTITY,
	column1_doubled INT,
	column2_doubled INT
);

INSERT INTO airflow_example(column1, column2)
VALUES (1111, 111111);

INSERT INTO airflow_example(column1, column2)
VALUES (2222, 222222);
