CREATE SCHEMA airflow_xcom_example;

CREATE TABLE airflow_xcom_example.example_table(
	id			INT	GENERATED BY DEFAULT AS IDENTITY,
	column1 INT,
	column2 INT
);

CREATE TABLE airflow_xcom_example.example_table_doubled(
	doubled_id			INT	GENERATED BY DEFAULT AS IDENTITY,
	column1_doubled INT,
	column2_doubled INT
);

INSERT INTO airflow_xcom_example.example_table(column1, column2)
VALUES (1111, 111111);

INSERT INTO airflow_xcom_example.example_table(column1, column2)
VALUES (2222, 222222);
